var english = {
    'login': 'Sign in',
    'register' : 'Sign up',
    'capabilities': 'Capabilities',
    'price': "Prices",
    'password':'Password',
    'email': 'Email',
    'close': 'close',
    'confirm': 'Confirm',
    'or': 'or',
    'create': 'Create',
    'demo': 'Demo',
    'show password': 'Show password',
    'hide password': 'Hide password',



    'social-media_msg': 'Our social medias',
    'tell_what_you_think_msg': 'Tell us what you think',
    'drag-n-drop-msg':'or drop image here',
    'sample_title_text':'Try it out',
    'sample_subtitle_text':'Click image to find similar items',
    'our_partners_msg':'Our partners',
    'become_a_partner_msg':'Want to become uor partner?',
    'partnership_msg':'Click the button below and we will contact you',
    'become_a_partner_btn_msg':'Become a partner',

    'name_label_msg':'Your name',
    'company_label_msg':'Your shop',
    'chosen_contact_msg':'Prefered contact',
    'explain_partnership_msg':'Additional info',
    'send_msg':'Send',

    'crop_img_msg':'Crop image',
    'apply':'Apply',


    'click_here_to_feedback_msg':'Click here to drop a message',
    'blog_msg':'blog',
    'vacancy_msg':'vacancy',
    'about_us_msg':'about us',
    'privacy_msg':'privacy',
    'terms_msg':'terms and conditions',
    'chose-file_msg':'Choose image',
    'chose-file':'Choose image',
    'crop-again-msg':'Crop again',
    'lower_msg':'Pants',
    'bags_msg':'Bags',
    'upper_msg':'Top',
    'boots_msg':'Shoes',
    'add_date_msg':'By add date',
    'price_msg':'By price',
    'popularity_msg':'By popularity',
    'sort_msg':'Sort by',
    'brand_filter_msg':'Filter by brand',
    'color_filter_msg':'Filter by color',
    'search_input_msg':'I search for...',
    'seller_filter_msg':'Filter by seller',
    'gender_filter_msg':'Filter by gender',
    'male':'Male',
    'female':'Female',
    'currency_msg':'$',
    'seller_msg':'Seller',
    'find_similar_msg':'Find similar',

    'red':'Red',
    'orange':'Orange',
    'yellow':'Yellow',
    'green':'Green',
    'blue':'Blue',
    'purple':'Purple',
    'black':'Black',
    'white':'White',

    'load_msg1':'Loading image',
    'load_msg2':'Processing image',
    'load_msg3':'Recieving suggestions',
    'load_msg4':'Please wait',
    'load_msg5':'Something went wrong',

    'short sleeve top':'Short sleeve top',
    'long sleeve top':'Long sleeve top',
    'short sleeve outwear':'Short sleeve outwear',
    'long sleeve outwear':'Long sleeve outwear',
    'vest':'Vest',
    'sling':'Sling',
    'shorts':"Shorts",
    'skirt':'Skirt',
    'trousers':'Trousers',
    'short sleeve dress':'Short sleeve dress',
    'long sleeve dress':'Long sleeve dress',
    'vest dress':'Vest dress',
    'sling dress':'Sling dress',
}

export default english