var russian = {
    'login': 'Войти',
    'register' : 'Регистрация',
    'capabilities': 'Возможности',
    'price': "Цены",
    'password':'Пароль',
    'email': 'Электронная почта',
    'close': 'Закрыть',
    'confirm': 'Подтвердить',
    'or': 'Или',
    'create': 'Создать',
    'demo': 'Демо',
    'show password': 'Показать пароль',
    'hide password': 'Спрятать пароль',

    'social-media_msg': 'Наши социальные сети',
    'tell_what_you_think_msg': 'Расскажите свое мнение',
    'drag-n-drop-msg':'или перетащите файл сюда',
    'sample_title_text':'Попробуйте',
    'sample_subtitle_text':'Нажмите на любое изображение, чтобы найти похожую одежду',
    'our_partners_msg':'Наши партнеры',
    'become_a_partner_msg':'Хотите стать партнером?',
    'partnership_msg':'Нажмите на кнопку ниже и мы с вами свяжемся',
    'become_a_partner_btn_msg':'Стать партнером',

    'name_label_msg':'Ваше имя',
    'company_label_msg':'Название магазина, который Вы представляете',
    'chosen_contact_msg':'Предпочтительный контакт',
    'explain_partnership_msg':'Дополнительная информация',
    'send_msg':'Отправить',

    'crop_img_msg':'Обрезать изображение',
    'apply':'Продолжить',

    'click_here_to_feedback_msg':'Нажмите здесь, чтобы оставить отзыв о сервисе',
    'blog_msg':'блог',
    'vacancy_msg':'вакансии',
    'about_us_msg':'о нас',
    'privacy_msg':'конфиденциальность',
    'terms_msg':'правила использования',
    'chose-file_msg':'Выберите файл',
    'chose-file':'Выберите файл',
    'crop-again-msg':'Обрезать снова',

    'lower_msg':'Брюки',
    'bags_msg':'Сумки',
    'upper_msg':'Футболки',
    'boots_msg':'Ботинки',

    'add_date_msg':'По дате добавления',
    'price_msg':'По цене',
    'popularity_msg':'По популярности',
    'sort_msg':'Сортировать',
    'brand_filter_msg':'Фильтр по бренду',
    'color_filter_msg':'Фильтр по цвету',
    'search_input_msg':'Я ищу...',
    'seller_filter_msg':'Фильтр по продавцу',
    'gender_filter_msg':'Фильтр по полу',
    'male':'Мужской',
    'female':'Женский',
    'currency_msg':'₽',
    'seller_msg':'Продавец',
    'find_similar_msg':'Найти похожее',

    'red':'Красный',
    'orange':'Оранжевый',
    'yellow':'Желтый',
    'green':'Зеленый',
    'blue':'Синий',
    'purple':'Фиолетовый',
    'black':'Черный',
    'white':'Белый',

    'load_msg1':'Загружаем изображение',
    'load_msg2':'Обрабатываем изображение',
    'load_msg3':'Подбираем результаты',
    'load_msg4':'Пожалуйста подождите',
    'load_msg5':'Что-то пошло не так',

    'short sleeve top':'Топ с короткими рукавами',
    'long sleeve top':'Топ с длинными рукавами',
    'short sleeve outwear':'Верхняя одежда с короткими рукавами',
    'long sleeve outwear':'Верхняя одежда с длинными рукавами',
    'vest':'Жилет',
    'sling':'Слинг',
    'shorts':"Шорты",
    'skirt':'Юбка',
    'trousers':'Штаны',
    'short sleeve dress':'Платье с короткими рукавами',
    'long sleeve dress':'Платье с длинными рукавами',
    'vest dress':'Платье-жилет',
    'sling dress':'Платье-слинг',




}

export default russian